apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangohelloworld-psql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          # Use the latest version of the myapp image
          image: macrosolid/djangohwpsql:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "ChangeIt1!"
            # - name: POSTGRES_DB  # This part brocke init phase
            #   value: "dbhelloworld"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume-mount
      volumes:
        - name: postgres-volume-mount
          # ./pvdata:/var/lib/postgresql/data
          persistentVolumeClaim:
            claimName: postgresql-data-claim
          # resource limits added for CPU and memory
          resources:
            requests:
              memory: "250Mi"
              cpu: "0.5"
            limits:
              memory: "500Mi"
              cpu: "1"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - "-U"
                - postgres
                - "-d"
                - dbhelloworld
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: postgres-volume-mount
          # ./pvdata:/var/lib/postgresql/data
          persistentVolumeClaim:
            claimName: postgresql-data-claim
      restartPolicy: Always
---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    name: postgres
# END SERVICE
